name: CI/CD for Gradio on Hugging Face Spaces

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 1: Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install evaluate  # For LLM metrics evaluation

      # Step 3: Run LLM tests (hallucination and BLEU score)
      - name: Run LLM tests
        run: |
          python test_llm.py

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Only deploy if the tests pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 1: Configure git for pushing to Hugging Face
      - name: Set up Git for Hugging Face
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      # Step 2: Push the app to Hugging Face Spaces
      - name: Push to Hugging Face Spaces
        run: |
          git add .
          git commit -m "Deploying new version to Hugging Face Spaces"
          git push https://${{ secrets.HF_TOKEN }}@huggingface.co/spaces/YourUsername/YourSpaceName HEAD:main